### ISSUE TITLE
snap not found

### ISSUE THREAD

**Issue by thsieh123** [boundarydevices/ubuntu-core#1]
$ sudo snap install ubuntu-image
error: cannot install "ubuntu-image": snap not found
$ snap --version
snap    2.23.1
snapd   2.23.1
series  16
ubuntu  16.04
kernel  4.8.0-41-generic

$ snapcraft -v
2.27.1

`sudo snap install hello-world`  works fine!

**Comment by gibsson** [comment]
Hi,

Can you try the following and let me know if it works for you?
$ sudo snap install ubuntu-image --devmode --edge

Regards,
Gary

**Comment by thsieh123** [comment]
It's working. The image also built with `make`.

**Comment by gibsson** [comment]
Thanks, will update the README then.
