### ISSUE TITLE
error: no snaps found

### ISSUE THREAD

**Issue by LZDSJTU** [boundarydevices/ubuntu-core#4]
Hello, I deleted some file of ubuntu core by mistake. And then I find that when I run 'snap list', it shows that 'error: no snap found'
Do you know how to deal with this problem?
Thank you very much!

**Comment by gibsson** [comment]
Hi,
No unfortunately I don't, maybe you should ask the ubuntu-core guys on IRC.
I'd suggest reflashing the whole image.
Regards
